### ISSUE TITLE
hi, I have a trouble when installing it. Could you give me some advice

### ISSUE THREAD

**Issue by xiexingxiang180** [erikbohnsack/murty#4]
ubuntu 18
Python 3.7

this is out message:

virtual-machine:~/murty$ make
git submodule update --init
pip3 install .
Processing /home/xie/murty
Installing collected packages: murty
  Running setup.py install for murty ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-28c9f93r-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dg1igieb-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_ext
    -- The C compiler identification is GNU 7.5.0
    -- The CXX compiler identification is GNU 7.5.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /usr/local/opt/python/bin/python3.7 (found version "1.4")
    CMake Error at pybind11/tools/FindPythonLibsNew.cmake:95 (message):
      Python config failure:
    
    Call Stack (most recent call first):
      pybind11/tools/pybind11Tools.cmake:16 (find_package)
      pybind11/CMakeLists.txt:33 (include)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-28c9f93r-build/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-28c9f93r-build/setup.py", line 107, in <module>
        packages=find_packages(exclude=['contrib', 'docs', 'tests*']),
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-28c9f93r-build/setup.py", line 44, in run
        self.build_extension(ext)
      File "/tmp/pip-28c9f93r-build/setup.py", line 68, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-28c9f93r-build', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-28c9f93r-build/build/lib.linux-x86_64-3.6', '-DPYTHON_EXECUTABLE=/usr/local/opt/python/bin/python3.7', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-28c9f93r-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-dg1igieb-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-28c9f93r-build/
Makefile:6: recipe for target 'install' failed
make: *** [install] Error 1
virtual-machine:~/murty$

**Comment by jurgisp** [comment]
I had exactly the same problem. You need to change https://github.com/erikbohnsack/murty/blob/master/setup.py#L49, which has hardcoded Python path `/usr/local/opt/python/bin/python3.7` to the python executable on your system.

**Comment by xiexingxiang180** [comment]
> I had exactly the same problem. You need to change https://github.com/erikbohnsack/murty/blob/master/setup.py#L49, which has hardcoded Python path `/usr/local/opt/python/bin/python3.7` to the python executable on your system.

Thank you very much！
